[package]
name = "async-demo"
version = "0.1.0"
authors = ["Tom"]
edition = "2018"

[dependencies]
futures = "0.3.0"
reqwest = {version = "0.10.0-alpha.1", features = ["json"]}
serde_json = "1.0"
tokio = "0.2.0-alpha.6"
